(function(){window.UD.registerSection("modernes-maerchen","profile",{
 title:"Stundenziel & Vorbereitung",eyebrow:"Realistische Einzelstunde",icon:"Z",description:"Ziel · Material · Schwierigkeiten",
 html:`
 <article class="goal-card"><span>Beobachtbares Stundenziel</span><p>Die Lernenden bestimmen am Gedicht das durchgängige Paarreimschema und verfassen einen Deutungssatz, in dem sie <strong>eine Formbeobachtung</strong>, <strong>einen Textbeleg</strong> und <strong>eine Wirkungserklärung</strong> miteinander verbinden.</p></article>
 <div class="content-grid two">
  <article class="content-card"><h3>Erfolgskriterien</h3><ol class="check-list"><li>Gleiche Endreime erhalten denselben Buchstaben.</li><li>Das Reimschema wird als Paarreim benannt.</li><li>Ein Gegensatz zwischen Form und Inhalt wird genannt.</li><li>Die Aussage wird mit Versen oder Zeilen belegt.</li><li>Die Wirkung wird erklärt.</li><li>Der Titel wird in einem vollständigen Satz gedeutet.</li></ol></article>
  <article class="content-card"><h3>Material</h3><dl class="material-list"><div><dt>M1</dt><dd>Text- und Aufgabenblatt</dd></div><div><dt>H1–H4</dt><dd>Gestufte Hilfekarten</dd></div><div><dt>L1</dt><dd>Musterlösung / Erwartungshorizont</dd></div><div><dt>vor Ort</dt><dd>Tafel oder Dokumentenkamera; zwei Textmarker</dd></div></dl></article>
 </div>
 <article class="content-card"><h3>Antizipierte Schwierigkeiten</h3><div class="responsive-table"><table><thead><tr><th>Hürde</th><th>Signal</th><th>Reaktion</th></tr></thead><tbody><tr><td>Reim und Reimschema werden verwechselt.</td><td>Ein Reimpaar wird genannt, aber kein Schema gebildet.</td><td>H1: Endwörter markieren, danach Buchstaben vergeben.</td></tr><tr><td>Formanalyse bleibt reines Abzählen.</td><td>Nur „aabb“ ohne Wirkung.</td><td>Leitfrage: Passt der geordnete Klang zu Armut und Enge?</td></tr><tr><td>„Geld macht unglücklich“ wird als einzige Aussage gesetzt.</td><td>Keine Belege oder Gegenbelege.</td><td>These einschränken und Fantasie, Armut sowie Reichtum vergleichen.</td></tr><tr><td>Sprachliche Unsicherheit.</td><td>Stichworte statt Erklärung.</td><td>H4: Beobachtung → Beleg → Erklärung.</td></tr></tbody></table></div></article>
 <div class="content-grid two"><article class="content-card success"><h3>Minimalfahrplan</h3><ol><li>Inhalt in drei Stationen aktivieren.</li><li>Reimpaare markieren und Paarreim sichern.</li><li>Einen Form-Inhalt-Kontrast herausarbeiten.</li><li>Titel in einem Satz deuten.</li></ol></article><article class="content-card danger"><h3>Notausstieg</h3><p>Bei Zeitverlust entfällt die Partner-Rückmeldung. Verbindlich gesichert werden Paarreim und Aufgabe 3b: „Der Titel ist …, weil …“</p></article></div>`
});})();