(function(){window.UD.registerSection("modernes-maerchen","sequence",{
 title:"Verlaufsplan",eyebrow:"45 Minuten · Form – Inhalt – Wirkung – Titel",icon:"V",description:"Phasen · Lernaktivität · Notausstieg",
 html:`<div class="responsive-table lesson-plan"><table><thead><tr><th>Zeit</th><th>Phase / Funktion</th><th>Lehrkraft</th><th>Lernaktivität</th><th>SF</th><th>Material / Sicherung</th><th>Differenzierung / Übergang</th></tr></thead><tbody>
 <tr><td><strong>0–5</strong></td><td><strong>Aktivierung</strong><br>Vorwissen bündeln</td><td>Drei Aussagen ungeordnet zeigen: „arm und verliebt“ – „reich und unglücklich“ – „Geld verschenkt“. Entwicklung ordnen und mit Stichworten ergänzen.</td><td>Reihenfolge herstellen; Inhalt reaktivieren; Widerspruch wahrnehmen.</td><td>EA → PA</td><td>Tafel / Folie<br><em>drei Pfeilstationen</em></td><td>Kein ausführliches Nacherzählen. Übergang: „Heute untersuchen wir, wie diese Entwicklung klingt.“</td></tr>
 <tr><td><strong>5–9</strong></td><td><strong>Textbegegnung</strong><br>Klang wahrnehmen</td><td>Gedicht ausdrucksstark vorlesen. Hörfrage: „Was fällt am Klang und an den Zeilenenden auf?“</td><td>Hören; erste Formbeobachtung äußern.</td><td>PL</td><td>M1 Gedichtblatt</td><td>Wortklärungen nur bei Bedarf.</td></tr>
 <tr><td><strong>9–20</strong></td><td><strong>Formanalyse</strong><br>Werkzeug aufbauen</td><td>Aufgabe 1 erläutern. Partner A: Z. 1–12, Partner B: Z. 13–22; anschließend Abgleich.</td><td>Endwörter markieren; Buchstaben vergeben; Strophenbau beschreiben; Reimschema benennen.</td><td>EA → PA</td><td>M1 · Aufgabe 1<br>H1 bei Bedarf</td><td>Basis: erste Reimpaare vormarkieren. Erweiterung: Wirkung der Schlussstrophe.</td></tr>
 <tr><td><strong>20–25</strong></td><td><strong>Zwischensicherung</strong><br>Begriffe klären</td><td>Durchgängigen Paarreim und Strophenbau sichern; Begründungen einfordern.</td><td>Ergebnis prüfen und Fachbegriffe präzisieren.</td><td>UG</td><td>Tafelbild Teil 1</td><td>Die vollständige Buchstabenfolge muss nicht abgeschrieben werden.</td></tr>
 <tr><td><strong>25–35</strong></td><td><strong>Vertiefung</strong><br>Form und Inhalt verknüpfen</td><td>Aufgabe 2: Wie klingt die Form? Welche Lebensumstände stehen daneben? Welche Wirkung entsteht?</td><td>Kontraste auswählen; Wirkungshypothese formulieren; Beleg zuordnen.</td><td>PA</td><td>M1 · Aufgabe 2<br>H2/H3</td><td>Erweiterung: These „Geld ist das Problem“ prüfen und einschränken.</td></tr>
 <tr><td><strong>35–42</strong></td><td><strong>Urteilssituation</strong><br>Titel deuten</td><td>Aufgabe 3 einzeln; anschließend 60-Sekunden-Partnercheck.</td><td>Deutung formulieren und anhand von Beobachtung, Beleg, Erklärung begründen.</td><td>EA → PA</td><td>M1 · Aufgabe 3<br>H4</td><td>Mehrere Positionen zulassen, sofern textgestützt.</td></tr>
 <tr><td><strong>42–45</strong></td><td><strong>Sicherung / Diagnose</strong></td><td>Zwei Sätze sammeln. Exit-Ticket: „Die geordnete Form wirkt …, obwohl …“</td><td>Kernsatz fertigstellen; Lernstand prüfen.</td><td>EA / PL</td><td>M1 / Heft</td><td>Diagnose: Form erkannt – Beleg vorhanden – Wirkung erklärt.</td></tr>
 </tbody></table></div><article class="content-card note"><strong>Puffer:</strong> Diskussion: Ist Reichtum im Gedicht wirklich Ursache des Unglücks – oder kritisiert der Text einfache Märchenlösungen?</article>`
});})();